name: Deploy

on:
  push:
    branches:
      - dev # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "callback5" #Must be unique in Heroku
          heroku_email: "blueridge05@gmail.com"
          branch: "dev"
          healthcheck: "https://callback.money"
          delay: 6
